language: node_js
node_js:
  - "4.2.1"
before_install:
  - npm install -g babel bower
after_script: "npm install coveralls@2.11.4 && cat ./target/coverage/server/lcov.info ./target/coverage/public/**/lcov.info | coveralls"
