language: node_js
node_js:
  - "5.0.0"
before_install:
  - "npm install -g bower"
after_script:
  - "npm install coveralls@2.11.4 && cat ./target/coverage/server/lcov.info ./target/coverage/public/**/lcov.info | coveralls"
